### ISSUE TITLE
Readability issues between 600 - 1300px breakpoints

### ISSUE THREAD

**Issue by leekinney** [elaconf/ela.community#2]
I just noticed the text over the colored background is really difficult to read (mostly the top 2 colors). I don't think I had looked at the site on a smaller screen til now 🙈
![screen shot 2017-03-27 at 5 05 08 pm](https://cloud.githubusercontent.com/assets/4022077/24378314/74749d72-1310-11e7-9206-d28ab225e3a6.png)

**Comment by katydecorah** [comment]
Oh darn! Thanks for flagging I thought I had fixed that! Will look into it
